import { createClient } from '@supabase/supabase-js'

const supabaseUrl = 'https://knstfqojgyerymnrphgf.supabase.co'
const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtuc3RmcW9qZ3llcnltbnJwaGdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY5NzM0NzYsImV4cCI6MjA1MjU0OTQ3Nn0.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtuc3RmcW9qZ3llcnltbnJwaGdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY5NzM0NzYsImV4cCI6MjA1MjU0OTQ3Nn0'

export const supabase = createClient(supabaseUrl, supabaseAnonKey)
